# if${ACCELERATOR} == DEVEL

SERVERNAME="steppermotor_"+STATION+"_server"
SVR_LOCATION=HOSTNAME.upper()+"."+STATION+"._SVR"
FACILITY="TEST.ACTUATOR"
DEVICE="MOTOR"
WATCHDOG_ADDRESS="TEST.SYSTEM/"+HOSTNAME.upper()+".WATCH/SVR.STEPPERMOTOR_"+STATION
