if ACCELERATOR == "MESA" :

  SERVERNAME="steppermotor_"+STATION+"_server"
  SVR_LOCATION=HOSTNAME.upper()+"."+STATION+"._SVR"
  FACILITY="MESA.ACTUATOR"
  DEVICE="MOTOR"
  WATCHDOG_ADDRESS="MESA.SYSTEM/"+HOSTNAME.upper()+".WATCH/SVR.STEPPERMOTOR_"+STATION

  RPC_NUMBER=610489684

  MAPFILE_BASENAME="controller_pzt4_md22_md22_fmc20_6s45_r"
  FIRMWARE_REV_MOTDRV ="2261"

  MOTORDRIVER_CFG_FILE="mesamotor.xml"
