if ACCELERATOR == "TARLA" :
  if STATION == "LLRF2" :
    #todo clean up MOTORDRIVER_CFG_FILE variable
    MAPFILE_BASENAME='llrf_resonance_ctrl_fmc25_'
    MOTORDRIVER_CFG_FILE="Limes122-MotorDriverCardConfig-Tarla.xml"
    
    MOTORS=["1"]
    MOTORDRIVERS=1

    MOTORDRIVER_SLOT=[3]
    MOTORDRIVER_NAME=["MotorDriver1"]

    MOTOR_DRIVER=[MOTORDRIVER_NAME[0]]
    MOTOR_DRIVERTYPE=["MD22"]
    MOTOR_TYPE=["LinearMotorWithReferenceSwitch"]
    MOTOR_MODULENAME=["FMC1"]
    MOTOR_DRIVERID=[0]
    MOTOR_MOTORDRIVERCONFIG=[MOTORDRIVER_CFG_FILE]
    MOTOR_MOTORSTEPSRATIO=[1]
    MOTOR_ENCODERSTEPSRATIO=[1]
    MOTOR_POSITIONUNIT=["steps"]
